kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: configuration-pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: blob-configuration
