apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cromwellazure-claim1
  name: cromwellazure-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
status: {}
