apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb-data-claim3
  name: mysqldb-data-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
status: {}
