apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\workspace\src\CromwellOnAzure\src\deploy-cromwell-on-azure\scripts\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tes
  name: tes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\workspace\src\CromwellOnAzure\src\deploy-cromwell-on-azure\scripts\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tes
    spec:
      containers:
        - env:
          image: mcr.microsoft.com/cromwellonazure/tes:2
          name: tes
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /datasettestinputs/dataset
              name: dataset-claim1
            - mountPath: /outputs
              name: outputs-claim1
      restartPolicy: Always
      volumes:
        - name: outputs-claim1
          persistentVolumeClaim:
            claimName: outputs-claim1
        - name: dataset-claim1
          persistentVolumeClaim:
            claimName: pvc-blob-dataset
status: {}
