apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\workspace\src\CromwellOnAzure\src\deploy-cromwell-on-azure\scripts\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: triggerservice
  name: triggerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: triggerservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\workspace\src\CromwellOnAzure\src\deploy-cromwell-on-azure\scripts\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: triggerservice
    spec:
      containers:
        - env:
          image: mcr.microsoft.com/cromwellonazure/triggerservice:2
          name: triggerservice
          resources: {}
      restartPolicy: Always
status: {}
